import crypto from 'crypto'
import { env } from '../../config/env'

/**
 * FaydaProvider — Official Fayda OIDC Integration
 *
 * Fayda is Ethiopia's national digital identity system built on eSignet (OpenID Connect).
 * Official base: https://esignet.ida.et
 *
 * This provider implements:
 *  1. Authorization URL generation with PKCE-less code flow + state nonce
 *  2. Authorization code → token exchange (POST to token endpoint)
 *  3. ID token verification via JWKS (or sandbox simulation)
 *
 * In FAYDA_SANDBOX_MODE=true (development):
 *  - No real Fayda calls are made
 *  - A simulated successful verification is returned
 *  - Credentials are NOT required
 *
 * In production:
 *  - Real OIDC flow against Fayda/eSignet endpoints
 *  - ID token JWT signature verified against Fayda JWKS
 */

export interface FaydaTokenResult {
  /** The raw ID token JWT from Fayda (NOT stored, only inspected) */
  idToken: string
  /** Access token (used to call userinfo if needed, NOT stored) */
  accessToken: string
}

export interface FaydaClaimsResult {
  /**
   * The Fayda subject identifier (opaque, stable per user per client).
   * Only a SHA-256 hash of this is stored in the database.
   * The raw value is NEVER logged or persisted.
   */
  sub: string
}

/**
 * Hash the Fayda `sub` claim using SHA-256.
 * This one-way hash is stored to enforce duplicate-account prevention
 * without retaining any raw identity data.
 */
export function hashFaydaSub(sub: string): string {
  return crypto.createHash('sha256').update(`fayda-sub:${sub}`).digest('hex')
}

/**
 * Build the Fayda OIDC authorization URL.
 * The `state` parameter is the anti-CSRF nonce generated by the verification service.
 */
export function buildAuthorizationUrl(state: string): string {
  if (env.FAYDA_SANDBOX_MODE) {
    // Sandbox: redirect straight back to our callback with a fake code
    const redirectUri = env.FAYDA_REDIRECT_URI || `${env.CLIENT_URL}/account/fayda/callback`
    const params = new URLSearchParams({
      code: 'sandbox_code',
      state,
    })
    return `${redirectUri}?${params.toString()}`
  }

  const clientId = env.FAYDA_CLIENT_ID
  const redirectUri = env.FAYDA_REDIRECT_URI
  const authUrl = env.FAYDA_AUTHORIZATION_URL

  if (!clientId || !redirectUri || !authUrl) {
    throw new Error(
      'Fayda OIDC is not configured. ' +
      'Set FAYDA_CLIENT_ID, FAYDA_REDIRECT_URI, and FAYDA_AUTHORIZATION_URL in .env, ' +
      'or set FAYDA_SANDBOX_MODE=true for development.',
    )
  }

  const params = new URLSearchParams({
    response_type: 'code',
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: 'openid',          // minimal scope — only sub claim required
    state,
    nonce: state,             // reuse state as nonce (single use)
    acr_values: 'mosip:idp:acr:static-code', // Fayda eSignet supported ACR
  })

  return `${authUrl}?${params.toString()}`
}

/**
 * Exchange an authorization code for tokens.
 * Returns { idToken, accessToken }.
 * The tokens are used immediately for claim extraction and then discarded.
 * NEVER logged.
 */
export async function exchangeCodeForToken(code: string): Promise<FaydaTokenResult> {
  if (env.FAYDA_SANDBOX_MODE) {
    if (code === 'sandbox_code' || code.startsWith('sandbox_code') || code === 'sandbox_duplicate_code') {
      // Sandbox simulation: return a fake ID token payload
      return {
        idToken: code === 'sandbox_duplicate_code' ? 'sandbox.duplicate.token' : 'sandbox.id.token',
        accessToken: 'sandbox.access.token',
      }
    }
    throw new Error('Sandbox mode received unexpected code.')
  }

  const tokenUrl = env.FAYDA_TOKEN_URL
  const clientId = env.FAYDA_CLIENT_ID
  const clientSecret = env.FAYDA_CLIENT_SECRET
  const redirectUri = env.FAYDA_REDIRECT_URI

  if (!tokenUrl || !clientId || !clientSecret || !redirectUri) {
    throw new Error('Fayda token endpoint not configured.')
  }

  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    code,
    redirect_uri: redirectUri,
    client_id: clientId,
    client_secret: clientSecret,
  })

  const response = await fetch(tokenUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: body.toString(),
  })

  if (!response.ok) {
    // Do NOT log response body — may contain sensitive auth context
    throw new Error(`Fayda token exchange failed with status ${response.status}`)
  }

  const data = await response.json() as { id_token?: string; access_token?: string }

  if (!data.id_token || !data.access_token) {
    throw new Error('Fayda token response missing id_token or access_token.')
  }

  return { idToken: data.id_token, accessToken: data.access_token }
}

/**
 * Verify the ID token and extract the `sub` claim.
 *
 * In production: fetches JWKS from Fayda and validates the JWT signature.
 * In sandbox: returns a deterministic per-user fake sub or duplicate test sub.
 *
 * IMPORTANT: The raw sub is returned only for immediate hashing.
 * It must NEVER be logged, stored raw, or returned to the frontend.
 */
export async function verifyIdTokenAndExtractSub(idToken: string, fallbackUserId?: string): Promise<FaydaClaimsResult> {
  if (env.FAYDA_SANDBOX_MODE) {
    if (idToken === 'sandbox.duplicate.token') {
      return { sub: 'sandbox-fayda-sub-duplicate-identifier' }
    }
    // Per-user sandbox identity so each test account has a unique simulated Fayda identity in dev
    return { sub: fallbackUserId ? `sandbox-fayda-sub-${fallbackUserId}` : 'sandbox-fayda-sub-identifier' }
  }

  const jwksUrl = env.FAYDA_JWKS_URL
  if (!jwksUrl) throw new Error('FAYDA_JWKS_URL not configured.')

  // Decode the JWT header to find the kid
  const parts = idToken.split('.')
  if (parts.length !== 3) throw new Error('Invalid ID token format.')

  let header: { alg?: string; kid?: string }
  try {
    header = JSON.parse(Buffer.from(parts[0], 'base64url').toString('utf8'))
  } catch {
    throw new Error('Failed to decode ID token header.')
  }

  // Fetch JWKS
  const jwksResponse = await fetch(jwksUrl)
  if (!jwksResponse.ok) {
    throw new Error(`Failed to fetch Fayda JWKS (status ${jwksResponse.status})`)
  }
  const jwks = await jwksResponse.json() as { keys: Array<{ kid?: string; n?: string; e?: string; kty?: string }> }

  const key = jwks.keys.find((k) => k.kid === header.kid && k.kty === 'RSA')
  if (!key || !key.n || !key.e) {
    throw new Error('No matching key found in Fayda JWKS.')
  }

  // Construct the public key from RSA components
  const publicKey = crypto.createPublicKey({
    key: {
      kty: 'RSA',
      n: key.n,
      e: key.e,
    },
    format: 'jwk',
  })

  // Verify the signature
  const signingInput = `${parts[0]}.${parts[1]}`
  const signature = Buffer.from(parts[2], 'base64url')
  const alg = header.alg || 'RS256'
  const nodeAlg = alg === 'RS256' ? 'RSA-SHA256' : alg

  const isValid = crypto.verify(nodeAlg, Buffer.from(signingInput), publicKey, signature)
  if (!isValid) {
    throw new Error('Fayda ID token signature verification failed.')
  }

  // Decode claims
  let claims: { sub?: string; exp?: number; iss?: string }
  try {
    claims = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'))
  } catch {
    throw new Error('Failed to decode ID token claims.')
  }

  // Validate expiry
  if (claims.exp && Date.now() / 1000 > claims.exp) {
    throw new Error('Fayda ID token has expired.')
  }

  if (!claims.sub) {
    throw new Error('Fayda ID token missing sub claim.')
  }

  return { sub: claims.sub }
}
